config/routes.rb
Rails.application.routes.draw do
  get "articles/index"
  get "articles/show"
  get "articles/new"
  get "articles/edit"
  resources :articles
  root to: 'articles#index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :published)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="article">
 <h5><%= article.title %></h5>
 </br>
 <p><%= article.body %></p>
 </br>
 <p>Status: <%= article.published ? 'Published' : 'Draft' %></p>
</div>


<%= link_to 'Edit', edit_article_path(article) %> |
<%= link_to 'Back', articles_path %>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
 <% if article.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>


     <ul>
       <% article.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
     </ul>
   </div>
 <% end %>


 <div class="field">
   <%= form.label :title %>
   <%= form.text_field :title %>
 </div>


 <div class="field">
   <%= form.label :body %>
   <%= form.text_area :body %>
 </div>


 <div class="field">
   <%= form.label :published %>
   <%= form.check_box :published %>
 </div>
<div class="actions">
   <%= form.submit %>
 </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>


<%= render "form", article: @article %>


<br>


<div>
 <%= link_to "Show this article", @article %> |
 <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div class="container mx-auto">
  <h1 class="text-3xl font-bold mb-4">Articles</h1>

  <%= link_to 'New Article', new_article_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4" %>

  <table class="w-full border-collapse border border-blue-500">
    <thead class="bg-blue-100">
      <tr>
        <th class="border border-blue-500 px-4 py-2">Title</th>
        <th class="border border-blue-500 px-4 py-2">Body</th>
        <th class="border border-blue-500 px-4 py-2">Published</th>
        <th class="border border-blue-500 px-4 py-2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td class="border border-blue-500 px-4 py-2"><%= article.title %></td>
          <td class="border border-blue-500 px-4 py-2"><%= article.body %></td>
          <td class="border border-blue-500 px-4 py-2"><%= article.published %></td>
          <td class="border border-blue-500 px-4 py-2">
            <%= link_to 'Show', article_path(article), class: "bg-green-500 hover:bg-green-500 text-white font-bold py-2 px-4 rounded mr-2" %>
            <%= link_to 'Edit', edit_article_path(article), class: "bg-yellow-500 hover:bg-yellow-500 text-white font-bold py-2 px-4 rounded mr-2" %>
            <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
</td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>


<%= render "form", article: @article %>


<br>


<div>
 <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PpWorkshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>